export const movieGenres = [
	{name: "TUTTI I FILM", value: "" },
	{name: "ANIMAZIONE", value: "Animazione" },
	{name: "AVVENTURA", value: "Avventura" },
	{name: "AZIONE", value: "Azione" },
	{name: "COMMEDIA", value: "Commedia" },
	{name: "CRIME", value: "Crime" },
	{name: "DOCUMENTARIO", value: "Documentario" },
	{name: "DRAMMA", value: "Dramma" },
	{name: "FAMIGLIA", value: "Famiglia" },
	{name: "FANTASCIENZA", value: "Fantascienza" },
	{name: "FANTASY", value: "Fantasy" },
	{name: "FILM IN TV", value: "Televisione Film" },
	{name: "GUERRA", value: "Guerra" },
	{name: "HORROR", value: "Horror" },
	{name: "MISTERO", value: "Mistero" },
	{name: "MUSICA", value: "Musica" },
	{name: "ROMANCE", value: "Romance" },
	{name: "STORIA", value: "Storia" },
	{name: "THRILLER", value: "Thriller" },
	{name: "WESTERN", value: "Western" },
];

export const tvGenres = [
	{name: "TUTTE LE SERIE TV", value: "" },
	{name: "ANIMAZIONE", value: "Animazione" },
	{name: "AVVENTURA", value: "Avventura" },
	{name: "AZIONE & AVVENTURA", value: "Action & Adventure" },
	{name: "AZIONE", value: "Azione" },
	{name: "BAMBINI", value: "Kids" },
	{name: "COMMEDIA", value: "Commedia" },
	{name: "CRIME", value: "Crime" },
	{name: "DOCUMENTARIO", value: "Documentario" },
	{name: "DRAMMA", value: "Dramma" },
	{name: "FAMIGLIA", value: "Famiglia" },
	{name: "FANTASCIENZA", value: "Fantascienza" },
	{name: "FANTASY", value: "Fantasy" },
	{name: "GUERRA & POLITICA", value: "War & Politics" },
	{name: "GUERRA", value: "Guerra" },
	{name: "HORROR", value: "Horror" },
	{name: "MISTERO", value: "Mistero" },
	{name: "MUSICA", value: "Musica" },
	{name: "REALITY", value: "Reality" },
	{name: "ROMANCE", value: "Romance" },
	{name: "SCIENZA & FANTASIA", value: "Sci-Fi & Fantasy" },
	{name: "SOAP", value: "Soap" },
	{name: "STORIA", value: "Storia" },
	{name: "TALK", value: "Talk" },
	{name: "THRILLER", value: "Thriller" },
	{name: "WESTERN", value: "Western" },
];
